In [25]:
import numpy as np

a = np.array([2,3,4], dtype=np.float)
print(a.dtype)
print(np.zeros((1,3,2)))
print(np.ones((1,3,2)))
# 使用未初始化内存，值不定
print(np.empty((1,3,2)))
# arange生成数列， reshape重新排列（维数相乘等于元素数量）
print(np.arange(12).reshape((3,2,2)))
# linspace生成数列
# linspace(起，止，数量)
print(np.linspace(1,20,6).reshape((3,2)))

float64
[[[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[ 1.   4.8]
 [ 8.6 12.4]
 [16.2 20. ]]


In [44]:
# numpy基础运算
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(b>3)
print(b+3)
# 矩阵的积
print(np.dot(a,b),a.dot(b))
# 生成随机矩阵
c = np.random.random((2,4))
print('c:',c)
# axis=0 列   axis=1 行
print('求和：',np.sum(c))
print('行求和', np.sum(c, axis=1))
print('列求和', np.sum(c, axis=0))
print('求最小值：',np.min(c))
print('求最大值：',np.max(c))

[10 20 30 40] [1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]
[False False False  True]
[4 5 6 7]
300 300
c: [[0.36427057 0.59625162 0.50673333 0.52661585]
 [0.96491174 0.54494306 0.74145797 0.14750445]]
求和： 4.392688596401845
行求和 [1.99387137 2.39881723]
列求和 [1.32918231 1.14119469 1.2481913  0.6741203 ]
求最小值： 0.1475044502121282
求最大值： 0.9649117426511192
